controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gimbal_controller:
      type: position_controllers/JointGroupPositionController

gimbal_controller:
  ros__parameters:
    joints:
      - yaw_joint
      - pitch_joint
